version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./worker/main.go
    goos:
      - linux
      - darwin

archives:
  - format: binary
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
