version: 2

builds:
  - id: dunebot
    env:
      - CGO_ENABLED=0
    main: ./worker/dunebot/main.go
    goos:
      - linux
      - darwin
  - id: engine-ci
    env:
      - CGO_ENABLED=0
    main: ./worker/engine-ci/main.go
    goos:
      - linux
      - darwin

archives:
    - id: dunebot                                                                                                                                     
      builds: [dunebot]                                                                                                                               
      formats: [binary]                                                                                                                               
      name_template: >-
        {{ .ProjectName }}_
        {{- .Os }}_
        {{- .Arch }}
        {{- if .Arm }}v{{ .Arm }}{{ end }}                                                                                          
                                                                                                                                                      
    - id: engine-ci                                                                                                                                   
      builds: [engine-ci]                                                                                                                             
      formats: [binary]                                                                                                                               
      name_template: >-
        {{ .ProjectName }}_
        {{- .Os }}_
        {{- .Arch }}
        {{- if .Arm }}v{{ .Arm }}{{ end }}     