version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./worker/main.go
    goos:
      - linux
      - darwin

archives:
  - format: binary
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
