name: Go service workflow

on:
  pull_request:
    branches:
      - main

concurrency:
  group: temporal_worker_${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout
  id-token: write # for authenticating to Google Cloud Platform
  pull-requests: write # for updating pr

jobs:
  build:
    uses: ./.github/workflows/containifyci.yaml
    secrets: inherit
